import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/models/models.dart';
import '../../core/providers/providers.dart';
import '../../shared/theme/app_theme.dart';

// ════════════════════════════════════════════════════════════════════════════
// YAML IMPORT PAGE — paste, validate, resolve conflicts, commit
// ════════════════════════════════════════════════════════════════════════════

class YamlImportPage extends ConsumerStatefulWidget {
  const YamlImportPage({super.key});

  @override
  ConsumerState<YamlImportPage> createState() => _YamlImportPageState();
}

class _YamlImportPageState extends ConsumerState<YamlImportPage> {
  final _textCtrl = TextEditingController();
  bool _hasParsed = false;

  @override
  void dispose() {
    _textCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final importState = ref.watch(yamlImportProvider);

    return Scaffold(
      backgroundColor: AppColors.background,
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Padding(
              padding: const EdgeInsets.fromLTRB(
                  AppSpacing.xl, AppSpacing.xl, AppSpacing.xl, AppSpacing.md),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Import YAML', style: AppTypography.pageTitle),
                  const SizedBox(height: 4),
                  Text(
                    'Paste the YAML generated by your AI assistant.',
                    style: AppTypography.caption,
                  ),
                ],
              ),
            ),

            Expanded(
              child: importState.when(
                data: (result) {
                  if (!_hasParsed || result == null) {
                    return _PasteView(
                      textCtrl: _textCtrl,
                      onParse: () {
                        if (_textCtrl.text.trim().isEmpty) return;
                        setState(() => _hasParsed = true);
                        ref.read(yamlImportProvider.notifier).parse(_textCtrl.text);
                      },
                    );
                  }
                  return _ResultView(
                    result: result,
                    onReset: () {
                      setState(() => _hasParsed = false);
                      ref.read(yamlImportProvider.notifier).reset();
                    },
                    onCommit: () async {
                      await ref.read(yamlImportProvider.notifier).commitImport(result);
                      if (context.mounted) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(content: Text('Goals imported successfully!')),
                        );
                        setState(() => _hasParsed = false);
                        ref.read(pageIndexProvider.notifier).state = 0;
                      }
                    },
                  );
                },
                loading: () => const Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      CircularProgressIndicator(color: AppColors.accentBlue),
                      SizedBox(height: 16),
                      Text('Validating YAML…', style: TextStyle(color: AppColors.textSecondary)),
                    ],
                  ),
                ),
                error: (e, _) => Center(
                  child: Text('Error: $e',
                      style: AppTypography.body.copyWith(color: AppColors.accentRed)),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ── Paste view ─────────────────────────────────────────────────────────────

class _PasteView extends StatelessWidget {
  final TextEditingController textCtrl;
  final VoidCallback onParse;
  const _PasteView({required this.textCtrl, required this.onParse});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(
          AppSpacing.xl, 0, AppSpacing.xl, AppSpacing.xl),
      child: Column(
        children: [
          // Example hint
          Container(
            padding: const EdgeInsets.all(AppSpacing.lg),
            decoration: BoxDecoration(
              color: AppColors.accentBlueDim.withValues(alpha: 0.2),
              borderRadius: AppRadius.card,
              border: Border.all(color: AppColors.accentBlue.withValues(alpha: 0.3)),
            ),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.info_outline, size: 14, color: AppColors.accentBlue),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'Paste your YAML below. Use the AI Prompt page to generate it from an AI chat.',
                    style: AppTypography.caption.copyWith(height: 1.5),
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 12),

          // Text area
          Expanded(
            child: Container(
              decoration: BoxDecoration(
                color: AppColors.surfaceAlt,
                borderRadius: AppRadius.card,
                border: Border.all(color: AppColors.border),
              ),
              child: TextField(
                controller: textCtrl,
                maxLines: null,
                expands: true,
                style: AppTypography.code.copyWith(fontSize: 12, height: 1.6),
                decoration: InputDecoration(
                  hintText: 'version: "1.0"\ngoals:\n  - id: my_goal\n    name: "My Goal"\n    ...',
                  hintStyle: AppTypography.code.copyWith(
                      fontSize: 11,
                      color: AppColors.textSecondary.withValues(alpha: 0.5)),
                  border: InputBorder.none,
                  contentPadding: const EdgeInsets.all(AppSpacing.lg),
                ),
              ),
            ),
          ),

          const SizedBox(height: 16),

          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              onPressed: onParse,
              child: const Text('Validate YAML'),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Result view ────────────────────────────────────────────────────────────

class _ResultView extends StatefulWidget {
  final YamlImportResult result;
  final VoidCallback onReset;
  final VoidCallback onCommit;
  const _ResultView({
    required this.result,
    required this.onReset,
    required this.onCommit,
  });

  @override
  State<_ResultView> createState() => _ResultViewState();
}

class _ResultViewState extends State<_ResultView> {
  @override
  Widget build(BuildContext context) {
    final r = widget.result;
    final canCommit = r.validGoals.isNotEmpty ||
        r.conflictGoals.any((g) => !g.skipOnConflict);

    return Padding(
      padding: const EdgeInsets.fromLTRB(
          AppSpacing.xl, 0, AppSpacing.xl, AppSpacing.xl),
      child: Column(
        children: [
          // Summary row
          _SummaryRow(
            valid: r.validGoals.length,
            conflicts: r.conflictGoals.length,
            errors: r.errors.length,
          ),

          const SizedBox(height: 12),

          Expanded(
            child: ListView(
              children: [
                // Errors
                if (r.errors.isNotEmpty) ...[
                  Text('ERRORS', style: AppTypography.sectionHeader),
                  const SizedBox(height: 6),
                  ...r.errors.map((e) => _ErrorCard(message: e)),
                  const SizedBox(height: 16),
                ],

                // Valid goals
                if (r.validGoals.isNotEmpty) ...[
                  Text('VALID GOALS', style: AppTypography.sectionHeader),
                  const SizedBox(height: 6),
                  ...r.validGoals.map((g) => _GoalCard(
                        name: g.name,
                        tasks: g.tasks.length,
                        badge: 'New',
                        badgeColor: AppColors.accentBlue,
                        trailingWidget: const Icon(Icons.check_circle_outline, color: AppColors.success, size: 18),
                      )),
                  const SizedBox(height: 16),
                ],

                // Conflicts
                if (r.conflictGoals.isNotEmpty) ...[
                  Text('CONFLICTS — Goal IDs already in your database', style: AppTypography.sectionHeader),
                  const SizedBox(height: 6),
                  ...r.conflictGoals.map((g) => _ConflictCard(
                        goalData: g,
                        onSkipChanged: (skip) {
                          setState(() => g.skipOnConflict = skip);
                        },
                      )),
                  const SizedBox(height: 16),
                ],
              ],
            ),
          ),

          // Action buttons
          Row(
            children: [
              Expanded(
                child: OutlinedButton(
                  onPressed: widget.onReset,
                  child: const Text('Edit YAML'),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: ElevatedButton(
                  onPressed: canCommit ? widget.onCommit : null,
                  child: const Text('Import Goals'),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _SummaryRow extends StatelessWidget {
  final int valid;
  final int conflicts;
  final int errors;
  const _SummaryRow({required this.valid, required this.conflicts, required this.errors});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        _SummaryBadge('$valid valid', AppColors.success),
        const SizedBox(width: 8),
        if (conflicts > 0) _SummaryBadge('$conflicts conflict${conflicts > 1 ? 's' : ''}', AppColors.warning),
        if (conflicts > 0) const SizedBox(width: 8),
        if (errors > 0) _SummaryBadge('$errors error${errors > 1 ? 's' : ''}', AppColors.accentRed),
      ],
    );
  }
}

class _SummaryBadge extends StatelessWidget {
  final String label;
  final Color color;
  const _SummaryBadge(this.label, this.color);

  @override
  Widget build(BuildContext context) => Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
        decoration: BoxDecoration(
          color: color.withValues(alpha: 0.15),
          borderRadius: AppRadius.chip,
          border: Border.all(color: color.withValues(alpha: 0.4)),
        ),
        child: Text(label,
            style: AppTypography.badge.copyWith(color: color, fontSize: 11)),
      );
}

class _ErrorCard extends StatelessWidget {
  final String message;
  const _ErrorCard({required this.message});

  @override
  Widget build(BuildContext context) => Container(
        margin: const EdgeInsets.only(bottom: 6),
        padding: const EdgeInsets.all(AppSpacing.md),
        decoration: BoxDecoration(
          color: AppColors.accentRedDim.withValues(alpha: 0.2),
          borderRadius: AppRadius.card,
          border: Border.all(color: AppColors.accentRed.withValues(alpha: 0.3)),
        ),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Icon(Icons.error_outline, color: AppColors.accentRed, size: 14),
            const SizedBox(width: 8),
            Expanded(
              child: Text(message,
                  style: AppTypography.caption.copyWith(color: AppColors.accentRed, height: 1.4)),
            ),
          ],
        ),
      );
}

class _GoalCard extends StatelessWidget {
  final String name;
  final int tasks;
  final String badge;
  final Color badgeColor;
  final Widget? trailingWidget;
  const _GoalCard({
    required this.name,
    required this.tasks,
    required this.badge,
    required this.badgeColor,
    this.trailingWidget,
  });

  @override
  Widget build(BuildContext context) => Container(
        margin: const EdgeInsets.only(bottom: 8),
        padding: const EdgeInsets.all(AppSpacing.lg),
        decoration: BoxDecoration(
          color: AppColors.surface,
          borderRadius: AppRadius.card,
          border: Border.all(color: AppColors.border),
        ),
        child: Row(
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(name, style: AppTypography.cardTitle),
                  Text('$tasks task${tasks == 1 ? '' : 's'}', style: AppTypography.caption),
                ],
              ),
            ),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(
                color: badgeColor.withValues(alpha: 0.15),
                borderRadius: AppRadius.chip,
              ),
              child: Text(badge,
                  style: AppTypography.badge.copyWith(color: badgeColor, fontSize: 10)),
            ),
            if (trailingWidget != null) ...[
              const SizedBox(width: 8),
              trailingWidget!,
            ],
          ],
        ),
      );
}

class _ConflictCard extends StatelessWidget {
  final YamlGoalData goalData;
  final ValueChanged<bool> onSkipChanged;
  const _ConflictCard({required this.goalData, required this.onSkipChanged});

  @override
  Widget build(BuildContext context) => Container(
        margin: const EdgeInsets.only(bottom: 8),
        padding: const EdgeInsets.all(AppSpacing.lg),
        decoration: BoxDecoration(
          color: AppColors.surface,
          borderRadius: AppRadius.card,
          border: Border.all(color: AppColors.warning.withValues(alpha: 0.4)),
        ),
        child: Row(
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(goalData.name, style: AppTypography.cardTitle),
                  Text('ID already exists', style: AppTypography.caption.copyWith(color: AppColors.warning)),
                ],
              ),
            ),
            Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                GestureDetector(
                  onTap: () => onSkipChanged(false),
                  child: _ConflictOption(
                    label: 'Overwrite',
                    selected: !goalData.skipOnConflict,
                    color: AppColors.accentRed,
                  ),
                ),
                const SizedBox(height: 4),
                GestureDetector(
                  onTap: () => onSkipChanged(true),
                  child: _ConflictOption(
                    label: 'Skip',
                    selected: goalData.skipOnConflict,
                    color: AppColors.textSecondary,
                  ),
                ),
              ],
            ),
          ],
        ),
      );
}

class _ConflictOption extends StatelessWidget {
  final String label;
  final bool selected;
  final Color color;
  const _ConflictOption({required this.label, required this.selected, required this.color});

  @override
  Widget build(BuildContext context) => AnimatedContainer(
        duration: const Duration(milliseconds: 150),
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
        decoration: BoxDecoration(
          color: selected ? color.withValues(alpha: 0.15) : Colors.transparent,
          borderRadius: AppRadius.chip,
          border: Border.all(
            color: selected ? color : AppColors.border,
          ),
        ),
        child: Text(label,
            style: AppTypography.badge.copyWith(
                color: selected ? color : AppColors.textSecondary, fontSize: 11)),
      );
}
